png(filename = "plot3.png",width = 480, height = 480,units = "px")
power1<-read.table("household_power_consumption.txt", sep=";", na.strings="?", header= TRUE)
power1$datetime<-paste(power1$Date," ",power1$Time)
power1$final<-strptime(power1$datetime, "%d/%m/%Y %H:%M:%S")
power<-subset(power1,((as.Date(power1$final, "%d/%m/%Y %H:%M:%S") == "2007-02-01") | (as.Date(power1$datetime, "%d/%m/%Y %H:%M:%S") == "2007-02-02")))
with(power,plot(final, Sub_metering_1, type="l",ylab="Energy sub metering",xlab=""))
with(power,lines(final, Sub_metering_2, type="l",ylab="Energy sub metering", col="red"))
with(power,lines(final, Sub_metering_3, type="l",ylab="Energy sub metering", col="blue"))
legend("topright",pch="-",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()