png(filename = "plot4.png",width = 480, height = 480,units = "px")
power1<-read.table("household_power_consumption.txt", sep=";", na.strings="?", header= TRUE)
power1$datetime<-paste(power1$Date," ",power1$Time)
power1$final<-strptime(power1$datetime, "%d/%m/%Y %H:%M:%S")
power<-subset(power1,((as.Date(power1$final, "%d/%m/%Y %H:%M:%S") == "2007-02-01") | (as.Date(power1$datetime, "%d/%m/%Y %H:%M:%S") == "2007-02-02")))
par(mfrow=c(2,2))
with(power, {
  plot(power$final, power$Global_active_power, type="l",ylab="Global Active Power", xlab="")
  plot(power$final, power$Voltage, type="l",ylab="Voltage",xlab="datetime")
  plot(final, Sub_metering_1, type="l",ylab="Energy sub metering",xlab="")
  lines(final, Sub_metering_2, type="l",ylab="Energy sub metering", col="red")
  lines(final, Sub_metering_3, type="l",ylab="Energy sub metering", col="blue")
  legend("topright",pt.cex=1, cex=0.5,pch="-",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
  plot(power$final, power$Global_reactive_power, type="l",ylab="Global_rective_power",,xlab="datetime")
})
dev.off()